export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const GET_REPOS = "GET_REPOS";
export const NO_REPOS = "NO_REPOS";

export const PROFILE_ERROR = "PROFILE_ERROR";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_USER_CART = "GET_USER_CART";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_ERROR = "GET_ERROR";
export const ADD_TO_CART = "ADD_TO_CART";
export const IN_PROGRESS = "IN_PROGRESS";
export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const CREATE_SHOP = "CREATE_SHOP";
export const GET_ALL_SHOPS = "GET_ALLSHOPS";
export const DELETE_SHOP = "DELETE_SHOP";
export const UPDATE_SHOP = "UPDATE_SHOP";
export const GET_USER_PRODUCTS = "GET_USER_PRODUCTS";
export const SHOP_ACTION_ATTEMPT = "SHOP_ACTION_ATTEMPT";
export const SHOP_ACTION_SUCCESS = "SHOP_ACTION_SUCCESS";
export const SHOP_ACTION_FAILED = "SHOP_ACTION_FAILED";
export const PRODUCT_ACTION_ATTEMPT = "PRODUCT_ACTION_ATTEMPT";
export const PRODUCT_ACTION_SUCCESS = "PRODUCT_ACTION_SUCCESS";
export const PRODUCT_ACTION_FAILED = "PRODUCT_ACTION_FAILED";
export const OrderActionAttempt = "OrderActionAttempt";
export const OrderActionFailed = "OrderActionFailed";
export const OrderActionSuccess = "OrderActionSuccess";
export const CreateOrder = "CreateOrder";
export const GET_DASHBOARD_ORDERS = "GET_DASHBOARD_ORDERS ";
export const GET_USER_ORDERS = "GET_USER_ORDERS ";
export const GET_SINGLE_ORDER = "GET_SINGLE_ORDER ";

export const CART_QUANTITY_INCREAMENT = "CART_QUANTITY_INCREAMENT";
export const CART_QUANTITY_DECREAMENT = "CART_QUANTITY_DECREAMENT";
export const ADD_CATAGERY = "ADD_CATAGERY";
export const GET_CATAGERY = "GET_CATAGERY";
export const GET_SINGLE_SHOP = "GET_SINGLE_SHOP";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const GET_ADDRESS = "GET_ADDRESS";
export const ADDRESS_ACTION_ATTEMPT = "ADDRESS_ACTION_ATTEMPT";
export const ADDRESS_ACTION_FAILED = "ADDRESS_ACTION_FAILED";
export const ADDRESS_ACTION_SUCCESS = "ADDRESS_ACTION_SUCCESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const SET_CURRENT_ADDRESS = "SET_CURRENT_ADDRESS";
export const CLEAR_CURRENT_ADDRESS = "CLEAR_CURRENT_ADDRESS";

export const GET_USER_SHOPS = "GET_USER_SHOPS";
export const ADD_PRODUCT_IMAGE = "ADD_PRODUCT_IMAGE";
export const DELETE_PRODUCT_IMAGE = "DELETE_PRODUCT_IMAGE";
export const CLEAR_PRODUCT_IMAGE = "CLEAR_PRODUCT_IMAGE";
export const GET_CATAGERY_LIST = "GET_CATAGERY_LIST";
export const GET_SINGLE_CATAGERY = "GET_SINGLE_CATAGERY";

export const ADD_BRAND = "ADD_BRAND";
export const GET_BRAND = "GET_BRAND";
export const BRAND_ACTION_ATTEMPT = "BRAND_ACTION_ATTEMPT";
export const BRAND_ACTION_FAILED = "BRAND_ACTION_FAILED";
export const BRAND_ACTION_SUCCESS = "BRAND_ACTION_SUCCESS";
export const PASSWORD_CHANGE = "PASSWORD_CHANGE";

export const DELETE_BRAND = "DELETE_BRAND";
export const UPDATE_BRAND = "UPDATE_BRAND";
export const CART_GRAND_TOTAL = "CART_GRAND_TOTAL";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const DELETE_PROFILE = "DELETE_PROFILE";
export const GET_PROFILE = "GET_PROFILE";
export const LOAD_STRIPE = "LOAD_STRIPE";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const UPDATE_CATAGERY = "UPDATE_CATAGERY";
export const SINGLE_CATAGERY_TREE = "SINGLE_CATAGERY_TREE";

export const PROFILE_ACTION_ATTEMPT = "PROFILE_ACTION_ATTEMPT";
export const PROFILE_ACTION_FAILED = "PROFILE_ACTION_FAILED";
export const PROFILE_ACTION_SUCCESS = "PROFILE_ACTION_SUCCESS";
export const PRODUCTS_BY_CATAGERY = "PRODUCTS_BY_CATAGERY";

export const STRIPE_ACCOUNT_CREATE = "STRIPE_ACCOUNT_CREATE";
export const ORDER_COMPLETE = "ORDER_COMPLETE";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";

export const SELLER_CONFIRM = "SELLER_CONFIRM";

export const GET_ALL_USERS = "GET_ALL_USERS ";
export const DELETE_USER = "DELETE_USER";
export const CART_ACTION_ATTEMPT = "CART_ACTION_ATTEMPT";
export const CART_ACTION_FAILED = "CART_ACTION_FAILED";
export const CART_ACTION_SUCCESS = "CART_ACTION_SUCCESS";